### ISSUE TITLE
Bin size default and ranges

### ISSUE THREAD

**Issue by aenieblas** [abennici/StockMonitoringTool#22]
Set bin size default value to 1, and range to 0.1 and 100. Bin sizes smaller than 1cm might be meaningful for short-lived species.

https://github.com/abennici/StockMonitoringTool/blob/bad1210832b434e477c157c99addc38066a1dcd2/ui/elefan/elefanGaUI.R#L33

AE question: how does this work with the bin size issues we had previously?

**Comment by aenieblas** [comment]
@tokami - With a default value of 1 for the bin size and the sample dataset, we get the error that then bin size cannot be lower than the bin size of the data (bin size of sample dataset is 2). What was the reasoning for setting the default to 1?

**Comment by tokami** [comment]
Both works fine. When I reviewed the code the default was 4cm, which is too high for most stocks I worked with. 1 or 2cm is equally fine as default. I recommend to catch the error if selected bin size is smaller than aggregation of provided data and set to bin size of data with warning message.

**Comment by aenieblas** [comment]
there is already a warning if the bin size is < the interval of the midlengths of the dataset. 

alexandre, would it be difficult to set the default value of bin size to the interval of the midlengths of the dataset? either that, or bin size default value=2.
