### ISSUE TITLE
All methods: VRE report does not upload to workspace

### ISSUE THREAD

**Issue by aenieblas** [abennici/StockMonitoringTool#48]
Report does not upload to private workspace/StockMonitoringTools folder of the VRE.

Relates to createWSfolder function availability on the infrastructure?

**Comment by eblondel** [comment]
We need to know where/how the app was used. If it was used locally (pulled from this Github repository) without specifying any token in the URL (as it is done in the VRE), then the workspace interaction can't work. @tokami can you clarify where/how did you access the app to get this issue?

**Comment by aenieblas** [comment]
Ah, no, sorry emmanuel, I didn't understand when we spoke that you were referring to these tickets - in fact, these were made by me last year using the last version of the SMT that was integrated on the VRE.

**Comment by eblondel** [comment]
ok! no problem so we can close! ;-) we will reopen it in case the new deployed app fails for that
