### ISSUE TITLE
CMSY: download sample file from VRE

### ISSUE THREAD

**Issue by aenieblas** [abennici/StockMonitoringTool#49]
get a warning that "csv can't be downloaded securely", but then I select "keep" and it proceeds to download without error

**Comment by eblondel** [comment]
@tokami this warning generally comes from the browser depending on the file origin and mixing between https for the browsed website and the resource that is access under http (which is considered as security risk by the browser). Can you clarify where/how did you access the SMT app to get this warning?
Thanks in advance

**Comment by aenieblas** [comment]
Sorry again - this was me, using the beta version of the SMT on the VRE. I just retested, and this does not bug for me anymore.

**Comment by eblondel** [comment]
no problem! ;-)
