### ISSUE TITLE
Elefan: ouput plots using sample dataset, default param

### ISSUE THREAD

**Issue by aenieblas** [abennici/StockMonitoringTool#50]
outputs are not as expected - growth curves and Thompson and bell curves look wrong on the VRE, has a prior been changed somewhere?

**Comment by eblondel** [comment]
@aenieblas can you clarify which Elefan method you test (Elefan, Elefan GA, or Elefan SA)?

**Comment by aenieblas** [comment]
again, my comment from last year. checking again with the beta SMT on the VRE, this no longer seems to display the same error.
