### ISSUE TITLE
all methods VRE: run time notification

### ISSUE THREAD

**Issue by aenieblas** [abennici/StockMonitoringTool#52]
Provide an estimated time for starting as the method is being run (e.g., "The application is starting, the default run takes approximately 30 seconds”)

Approximate run times on the VRE: 
CMSY 1-2 m
Elefan GA  30 - 60s
Elefan SA - 1m 30s
Elefan 2-4 m

**Comment by eblondel** [comment]
I believe this relates to #46 somehow...

**Comment by aenieblas** [comment]
yes, this was the comment that i suggested we follow up with instead of the progress bar, but the run times are only relevant for the sample dataset and default parameters. As we decided in the meeting just before, we would stick with the comment that the process may take some time, and then cutoff the method at 10 min as is is now

**Comment by eblondel** [comment]
Ok on my side I will investigate how a real progress bar could be set-up with methods of an external package. This is a general need we have with functions called in shiny which processing may take some time. I did something in the past, but the major difference is that all the R code was within the shiny app, not in a remote package
