### ISSUE TITLE
CMSY: interaction with workspace doesn't work

### ISSUE THREAD

**Issue by eblondel** [abennici/StockMonitoringTool#68]
Storagehub R scripts are not robust enough to be used in a shiny context, with several core issues (lack of portability of curl-based methods, issues to pass token from shiny session, etc).

This will be externalized in a proper package to ease storagehub / workspace interaction. Package is at https://github.com/eblondel/d4storagehub4R

**Comment by eblondel** [comment]
@abennici here's what we discussed after troubleshooting R storagehub script. Please try with your token and let me know if it works for you. When i have time i will try on a docker instance.

**Comment by abennici** [comment]
@eblondel thank you for this improvement, unfortunately it seems to freeze at 'Fetching user profile...'. Do you have any idea why?
